# Generated by Django 4.2.2 on 2023-06-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
        ('Review', '0002_alter_review_comment_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reviews', to='Patient.patient'),
        ),
    ]
