# Generated by Django 4.2.2 on 2023-06-28 06:34

import Appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(validators=[Appointment.models.validate_time_range])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(blank=True, choices=[('A', 'AViALABALE'), ('R', 'RESERVERD')], max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
