# Generated by Django 4.2.2 on 2023-06-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'AVAILABLE'), ('R', 'RESERVED')], default='A', max_length=1, null=True),
        ),
    ]
