<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-26 15:53
=======
# Generated by Django 4.2.2 on 2023-06-26 21:22
>>>>>>> aa1979b0426c63620f331414a9dd63dd206c0d3a

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
