<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-28 17:47
=======
# Generated by Django 4.2.2 on 2023-06-28 03:19
>>>>>>> 0f81a7b9d7a86ae0df43850cc435562c83c7403e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
