# Generated by Django 4.2.2 on 2023-06-26 15:53

import Doctor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('City', '0001_initial'),
        ('District', '0001_initial'),
        ('Specialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profLicenseNo', models.CharField(max_length=6, validators=[Doctor.models.validate_profLicenseNum])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='City.city')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='District.district')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Specialization.specialization')),
            ],
        ),
    ]
