# Generated by Django 4.2.2 on 2023-06-28 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('F', 'FREE'), ('R', 'RESERVED'), ('C', 'CANCLED')], max_length=1, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
