# Generated by Django 4.2.2 on 2023-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'RESERVED'), ('C', 'CANCELED'), ('D', 'DONE')], default='R', max_length=1, null=True),
        ),
    ]
