# Generated by Django 4.2.2 on 2023-06-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEditCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('V', 'Valid'), ('E', 'Expired')], default='V', max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_edit_codes', to='Patient.patient')),
            ],
            options={
                'verbose_name_plural': 'Medical Edit Codes',
            },
        ),
    ]
